# Generated by Django 5.2.14 on 2026-05-25 03:25

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                condition=models.Q(("is_published", True)),
                fields=["-created_at"],
                name="blog_post_pub_created_desc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="blog_post_title_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["body"], name="blog_post_body_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
