# Generated by Django 5.2.14 on 2026-05-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='blog_user_email_idx'),
        ),
    ]
